[project]
name = "grid-stress"
version = "0.1.0"
description = "Capstone Project on Forecasting the German Power Grid Load & Stability"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "scikit-learn",
    "statsmodels",
    "mlflow",
    "parsenvy",
]

[dependency-groups]
dev = [
    "jupyterlab",
    "seaborn",
    "pytest",
    "testbook",
    "black",
    "nbdime",
]

[tool.uv]
package = false
