"""Home page — project introduction.

Content is drawn from CLAUDE.md's project description and `risk-definition.ipynb` §1.7 (the
verified residual-load identity). No findings, metrics or conclusions are stated here — those
live on the EDA and Model pages, sourced from the notebooks that produced them.
"""

import streamlit as st

from streamlit.data_loading import get_years, load_smard

st.set_page_config(page_title="Grid Stress", page_icon="⚡", layout="wide")

st.title("Grid Stress — German Power Grid Load & Stability")

st.markdown(
    """
Capstone project forecasting the German power grid's load and stability from SMARD data
(Bundesnetzagentur).

**Objective.** Use installed power-plant, generation and consumption data to predict the power
Germany's grid needs one day ahead, and build a time-series model that spots days at risk of
intervention measures by the grid operators (TSOs).

**Problem statement.** Extreme values of **residual load** — the demand left after wind and
solar generation — are the project's risk cases:

- **high residual load** (imports, tight margins)
- **negative residual load** (renewable oversupply, negative prices, downward redispatch)

SMARD.de publishes its own day-ahead residual-load forecast, which this project uses as the
public baseline to beat.
"""
)

st.subheader("Residual load")
st.latex(r"\text{Residual Load} = \text{Grid Load} - \text{Wind Generation} - \text{Solar Generation}")
st.caption(
    "Verified against the loaded data in `risk-definition.ipynb` §1.7 "
    "(`residual_load == grid_load - wind_off - wind_on - solar`, to within rounding)."
)

st.subheader("Scope")
st.markdown(
    """
Generation features are limited to **wind and solar** — the project's day-ahead forecasting
baseline (SMARD's own forecasts) exists only for these two, and they are the largest variable
generation sources. Other generation (biomass, coal, hydro, ...) is out of scope.
"""
)

st.subheader("Data")
try:
    time_series = load_smard()
    years = get_years(time_series)
    st.markdown(
        f"- **{len(time_series):,} hourly rows**, "
        f"{time_series.index.min():%Y-%m-%d %H:%M} → {time_series.index.max():%Y-%m-%d %H:%M} "
        f"({years[0]}–{years[-1]})\n"
        f"- Source: SMARD API (`data/smard.csv`), regenerated by `notebooks/API-connection.ipynb`"
    )
except (FileNotFoundError, RuntimeError) as exc:
    st.warning(f"SMARD data not available: {exc}")

st.subheader("Pages")
st.markdown(
    """
- **EDA** — exploratory analysis of load, generation and residual load, from
  `notebooks/01_eda/team-EDA.ipynb`.
- **Model** — the project's risk-label definition and the SMARD forecast benchmark our own model
  will need to beat.
"""
)
